name: Buildroot

on: [push]

jobs:
    build:
        name: Build Buildroot image
        strategy:
          matrix:
            config: ["widora_mangopi_r3"]
        runs-on: ubuntu-latest
        container: debian:bullseye
        steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Build
          run: |
            export SRC_ROOT=$GITHUB_WORKSPACE
            export DEFCONFIG=${{ matrix.config }}_defconfig
            export BUILDROOT_DIR=/tmp/buildroot
            export BUILDROOT_RELEASE=2022.08.1
            export DEBIAN_FRONTEND=noninteractive 
            export DEBCONF_NONINTERACTIVE_SEEN=true
            apt update
            $SRC_ROOT/.devcontainer/library-scripts/install-dependencies.sh
            $SRC_ROOT/.devcontainer/build-scripts/download-buildroot.sh
            $SRC_ROOT/.devcontainer/build-scripts/build.sh
        - name: Archive Build artifacts
          uses: actions/upload-artifact@v3
          with:
            name: rootfs-ext2-${{ matrix.config }}
            path: /workspaces/buildroot/output/images/rootfs.ext2
